a = input('Digite algo:')
print(type(a))
print(a.isalnum())
print(a.isalpha())
print(a.isnumeric())
print(a.isascii())
print(a.isdigit())
print(a.isdecimal())
print(a.isidentifier())
print(a.isalpha())
print(a.islower())
print(a.isspace())
print(a.isprintable())
print(a.istitle())
print(a.isupper())
